### ISSUE TITLE
Release TODO

### ISSUE THREAD

**Issue by mrflix** [mrflix/dimensions#1]
- [x] Fix that Dimensions can be reactivated in the same tab without reload (bug appears when installed from Chrome Web Store)
- [x] Fix 'Add to Chrome' button on the website
- [x] wire links on the website
- [x] create extension screenshots and artwork for the store
